# Generated by Django 5.0.3 on 2024-05-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_alter_vuelo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asientos_reservados',
            field=models.IntegerField(default=1),
        ),
    ]
